### ISSUE TITLE
Problemas con login cuando lo haces desde el popup

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#146]
No funciona el login cuando lo haces con correo directamente sobre el documento o como resultado de picarle a "a favor" y en "en contra". Pones tus datos y le picas a ingresar y no pasa nada.

![screen shot 2015-02-23 at 11 42 24](https://cloud.githubusercontent.com/assets/5718530/6333264/2e37e8b4-bb51-11e4-8ecf-cdaaef65ebab.png)

**Comment by rodowi** [comment]
En mi ambiente local no pude replicar el error. Pude loggearme desde el popup, después de hacer doble click en el texto, y también desde el botón de votar.

**Comment by rodowi** [comment]
Igual pude hacer los 2 logins desde la versión de producción.

**Comment by rodowi** [comment]
En el botón de votar sí hay problema.

**Comment by rodowi** [comment]
Ya quedó con un cambio en el loadbalancer
