### ISSUE TITLE
Login-popup appears off-sight after attempting to add a comment or like

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#149]
Te sale en una esquina arriba que no ves si está tratando de dar like en un comentario ya hecho.

![screen shot 2015-02-23 at 11 57 12](https://cloud.githubusercontent.com/assets/5718530/6333540/7ecc21bc-bb53-11e4-8cbc-320cdd739e0c.png)
![screen shot 2015-02-23 at 12 00 41](https://cloud.githubusercontent.com/assets/5718530/6333557/a15538ae-bb53-11e4-9ad5-d64dcb6d6c9b.png)

**Comment by jipster** [comment]
Este es siento de los más pressing y básico de usabilidad @rodowi

**Comment by rodowi** [comment]
No está funcionando en layout de votos https://www.pivotaltracker.com/story/show/92395172
