### ISSUE TITLE
After adding comment, the page freezes

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#150]
Después de editar/comentar sobre el documento la pantalla se obscurece y parece como si se trabara. Hasta que vuelves a dar un click vuelve en sí. 

![screen shot 2015-02-23 at 12 08 51](https://cloud.githubusercontent.com/assets/5718530/6333737/23cb0dee-bb55-11e4-8b28-0a5af5d4efcc.png)

**Comment by rodowi** [comment]
ha de ser un lightbox que se rompe y no aparece

**Comment by codemoe** [comment]
This doesn't happen anymore... this issue should be closed

**Comment by rodowi** [comment]
@codemoe en qué commit o PR?

**Comment by codemoe** [comment]
No estoy seguro en que commit se hubiera resuelto pero hice muchas pruebas distintas y no logré replicar el error....

Tal vez la persona a la que le sucedió pueda revisarlo de nuevo.....

**Comment by rodowi** [comment]
ok, cc: @jipster

**Comment by jipster** [comment]
Ya encontré este issue tampoco.
