### ISSUE TITLE
Falta mensaje de no estás registrado

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#152]
Pensaba que ya estaba registrado y puse mis datos, pero cuando los escribo no me dice que mi password o usuario está mal ni me da la opción de registrarme por primera vez.

![screen shot 2015-02-23 at 12 25 04](https://cloud.githubusercontent.com/assets/5718530/6333986/28f633e6-bb57-11e4-9def-985e855374bb.png)

**Comment by rodowi** [comment]
![screen shot 2015-03-02 at 6 08 34 pm](https://cloud.githubusercontent.com/assets/705860/6453773/4696e548-c107-11e4-8fa6-8acc08397d71.png)
![screen shot 2015-03-02 at 6 09 17 pm](https://cloud.githubusercontent.com/assets/705860/6453774/46a820d8-c107-11e4-8a32-07ab70310611.png)

**Comment by rodowi** [comment]
@jipster quedó resuelto en #181 

El tema de que no te da opción para registrarse, eso fue porque le diste Ingresar. Desde que se abre el popup te da opción de the blue pill o the red pill.

![screen shot 2015-03-02 at 6 47 10 pm](https://cloud.githubusercontent.com/assets/705860/6454211/8d6a566c-c10c-11e4-9f3d-19c61196dc9d.png)
