### ISSUE TITLE
Registro con twitter no está funcionando

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#153]
Te deja poner tu usuario, pero no te redirecciona a participa

![screen shot 2015-02-23 at 12 30 01](https://cloud.githubusercontent.com/assets/5718530/6334073/c6336b1a-bb57-11e4-8b6d-94d160729753.png)

**Comment by rodowi** [comment]
Cerrado en https://github.com/mxabierto/madison/issues/146#issuecomment-76857505

![screen shot 2015-03-02 at 6 03 39 pm](https://cloud.githubusercontent.com/assets/705860/6453711/8368e328-c106-11e4-8547-bfde0d7833c4.png)
