### ISSUE TITLE
Ingreso con Facebook no da mensaje

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#154]
Cuando ingresas con facebook y te regresa al home no te avisa que si estás INGRESADO y el dropdown menu sigue apareciendo como si siguieras sin ingresar, pero cuando que le picas al documento ya estás dentro
![screen shot 2015-02-23 at 12 43 25](https://cloud.githubusercontent.com/assets/5718530/6334389/fb4d44a4-bb59-11e4-86d7-1f7f3b687d4c.png)
![screen shot 2015-02-23 at 12 46 08](https://cloud.githubusercontent.com/assets/5718530/6334392/fe8a16b0-bb59-11e4-952f-2098c688854d.png)

**Comment by rodowi** [comment]
Una pista puede ser que la config del load balancer, hace que se rompa el ciclo de oauth con Fb

cc: @urkonn

**Comment by rodowi** [comment]
http://httpd.apache.org/docs/2.2/mod/mod_proxy_balancer.html#stickyness_implementation

**Comment by rodowi** [comment]
Listo:

![screen shot 2015-03-02 at 6 01 34 pm](https://cloud.githubusercontent.com/assets/705860/6453686/32eb7d52-c106-11e4-91ab-53bc6e1ed096.png)
