### ISSUE TITLE
No te deja desloggearte 

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#159]
Le picas a salir varias veces y no te saca, hasta que le das reload.

![screen shot 2015-02-24 at 12 58 22](https://cloud.githubusercontent.com/assets/5718530/6356714/d915e550-bc24-11e4-8425-45321b6a8f56.png)

**Comment by rodowi** [comment]
Está relacionado con https://github.com/mxabierto/madison/issues/146#issuecomment-76857505

**Comment by rodowi** [comment]
![screen shot 2015-03-02 at 6 02 17 pm](https://cloud.githubusercontent.com/assets/705860/6453701/6776b32a-c106-11e4-9830-d81bd58d7e5f.png)
