### ISSUE TITLE
No hay mensaje/ventana de you are logged in o de no está correcto tu correo/contraseña

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#160]
![screen shot 2015-02-24 at 13 00 06](https://cloud.githubusercontent.com/assets/5718530/6356751/265234f4-bc25-11e4-9291-968ba13b94f3.png)

**Comment by rodowi** [comment]
El problema estaba relacionado a https://github.com/mxabierto/madison/issues/146#issuecomment-76857505

![screen shot 2015-03-02 at 6 51 07 pm](https://cloud.githubusercontent.com/assets/705860/6454258/1ea8b61e-c10d-11e4-8240-daf7586ea62f.png)
