### ISSUE TITLE
Need a call-to-action or instruction for the voting buttons

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#163]
botones de favor y en contra, no tienen una pregunta; agregar una frase ¿qué opinas de este doc?

**Comment by jipster** [comment]
Si. Igual en madison está support this document vs oppose this document. y eso lo hace más claro.

Entonces habría dos vía:

1. ¿Qué opinas de este documento?
A. Estoy a favor B. Estoy en contra

o

2.1. Estoy a favor de este documento 2.2 Estoy en contra de este documento
