### ISSUE TITLE
PSD con diseño

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/madison#18]

**Comment by diegobeauroyre** [comment]
Navbar debe ser igual que el de gob.mx

**Comment by diegobeauroyre** [comment]
@simiographics Acá esta el psd: https://drive.google.com/open?id=0B6xuFjlJEb0NZXFxWldYaThmaTQ&authuser=0

Falta el log-in y la parte del foro, en unos min lo actualizo

**Comment by simiographics** [comment]
Gracias Diego!

**Comment by diegobeauroyre** [comment]
:ok_hand:

**Comment by simiographics** [comment]
Bueno, no tengo permisos para bajarlo :(

**Comment by diegobeauroyre** [comment]
Ya está en la carpeta con PNGs y los colores unificados, 

@rodowi perdón, los había mezclado con los de dgm, los únicos colores que hay son: 

Off White: #eeeeee 

Gris claro: #d7d7d7
Gris obscuro: #545454

Negro 1: #28292a

Azul Claro: #4a90e2
Azul Obscuro: #1122cc

Verde Claro: #00cc99
Verde Obscuro: #00a699

Puse unos pngs también #porsi
