### ISSUE TITLE
Pop-up message (for email taken) is shown off-screen

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#186]
Cambiar copy de Email a correo electrónico también.

![screen shot 2015-03-03 at 08 57 09](https://cloud.githubusercontent.com/assets/5718530/6462046/69b70d82-c184-11e4-8829-47a71cd3fa4c.png)

**Comment by rodowi** [comment]
https://github.com/mxabierto/madison/blob/master/composer.json#L15
