### ISSUE TITLE
Agregar un nuevo layout para proyectos de votación

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#187]
- [x] Remover botones de "a favor" y "en contra"
- [x] Remover pestaña de "Petición" y dejar activa "Foro"
- [x] Cambiar nombre de pestaña "Foro" a "Propuestas"
- [x] Agregar instrucciones debajo del título "Comentarios" - "Vota por los conjuntos de datos que te interesan"
- [x] Cambiar "Comentarios" por "Categorías de Datos Abiertos Propuestos"
- [x] Esconder el autor de las propuestas
- [x] Cambiar "Add a comment" por "Sugiere otro conjunto"
- [x] Quitar el sidebar con "Anotaciones" y "Cómo participar"
- [x] El primer input es "Sugiere otra categoría", el segundo (el de subcomments) es "Sugiere otro conjunto" - [ver comentario para mayor explicación](https://github.com/mxabierto/madison/issues/187#issuecomment-82695995)

**Comment by rodowi** [comment]
![nuevolayout2](https://cloud.githubusercontent.com/assets/705860/6468229/4b625016-c199-11e4-8e08-78c92f550529.png)

**Comment by rodowi** [comment]
![screen shot 2015-03-03 at 11 25 59 am](https://cloud.githubusercontent.com/assets/705860/6468238/5a024d10-c199-11e4-8238-0a97bdcddd3e.png)

**Comment by rodowi** [comment]
WIP en #192

**Comment by rodowi** [comment]
Un requerimiento que rebotó el equipo y faltó plasmar en este issue es que la organización de comentarios y sugerencias será tener como primer nivel "Categorías" y segundo nivel (subcomentarios o comentarios-de-comentarios) serán "Conjuntos de datos".

![screen shot 2015-03-17 at 8 40 28 pm](https://cloud.githubusercontent.com/assets/705860/6701700/e4b57f02-cce5-11e4-9ac9-2beb8c70a32b.png)

**Comment by rodowi** [comment]
@urkonn es necesario pasar las credenciales a un .env.php con el layout de .env.example.php

**Comment by rodowi** [comment]
@urkonn también hay que darle un `composer install`

**Comment by urkonn** [comment]
me aparece esto al correr ```composer install```

```
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
```

```                                                                                                                                        
  [RuntimeException]                                                                                                                     
  The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages. 
```

**Comment by joecohens** [comment]
@rodowi Actualice mockery para que ya no les mande error de que no existe, lo que pasa es que estaba chocando con otro paquete. https://github.com/mxabierto/madison/commit/278d38c6c94234209ddd8bfe8a4c5f68f2401aa3

@urkonn Puedes hacer `composer install --no-dev` sin problemas para que no te mande ese error.

Saludos!

**Comment by rodowi** [comment]
Gracias, igual y hacemos `composer install --no-dev` porque ya creamos el tag en https://github.com/mxabierto/madison/releases/tag/v1.0.4, y este fix queda para después

**Comment by joecohens** [comment]
Perfecto no hay problema :)

**Comment by urkonn** [comment]
gracias @joecohens 
¿hay que instalar DotEnv para leer las variables de ambiente en .env.php ?

**Comment by joecohens** [comment]
@urkonn No es necesario, Laravel lo lee directo como un archivo php. Cualquier duda avísame.

Saludos!

**Comment by urkonn** [comment]
@joecohens ya se solucionó, cambié el nombre a .env.local.php

Saludos

**Comment by joecohens** [comment]
@urkonn Excelente!
