### ISSUE TITLE
Cleanup deps, config files, PSR-2 php

### ISSUE THREAD

**Issue by joecohens** [mxabierto/madison#188]

**Comment by rodowi** [comment]
El tema de YAML se actualizó acá:

https://github.com/mxabierto/madison/pull/110
https://github.com/mxabierto/madison/commit/e8355c2e0aa2a7a2b62471ced9258ff779a8b266

**Comment by joecohens** [comment]
@rodowi Si pero faltó mover los archivos de example_* https://github.com/mxabierto/madison/pull/189

**Comment by joecohens** [comment]
También falto limpiar los seeds que seguían haciendo referencia a los YAML, ya quedó todo eso en el PR :)

**Comment by rodowi** [comment]
awesome, de hecho creo que aventé un PR hace tiempo a madison sobre las referencias en los seeds, pero que bueno que ya quedó

está buena la limpieza

**Comment by rodowi** [comment]
@joecohens esto ya se puede cerrar no?

**Comment by joecohens** [comment]
Si si
