### ISSUE TITLE
No se ve el placeholder de Sugiere otro conjunto

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#198]
![screen shot 2015-03-18 at 4 33 08 pm](https://cloud.githubusercontent.com/assets/705860/6720828/8aa1412a-cd8c-11e4-978e-78a02bfad30b.png)

**Comment by rodowi** [comment]
Si abro otra ventana con mi sesión sí se ve. Parece que sólo sucede cuando agregas texto y se hace refresh.

**Comment by jipster** [comment]
Después de agregar un comentario la nueva caja de texto no tiene texto de placeholder automático

![image](https://cloud.githubusercontent.com/assets/5718530/7034915/a6118646-dd49-11e4-8e29-5c0e2c036637.png)

**Comment by rodowi** [comment]
Lo cierra #207 

![screen shot 2015-04-14 at 8 33 42 am](https://cloud.githubusercontent.com/assets/705860/7137673/f7675bc4-e280-11e4-8d1b-386f75d759b4.png)
