### ISSUE TITLE
Revisar el registro con FB

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/madison#199]
![image](https://cloud.githubusercontent.com/assets/6226604/6721177/d9f73e3e-cd8f-11e4-9aa0-16551b2a4f0e.png)

**Comment by rodowi** [comment]
@diegobeauroyre fue en producción o en QA?

yo no tuve problema en producción

**Comment by rodowi** [comment]
ya está en modo live el app en Fb

![screen shot 2015-03-18 at 5 25 26 pm](https://cloud.githubusercontent.com/assets/705860/6721542/ceb5d018-cd93-11e4-83a6-54ff63794457.png)

**Comment by urkonn** [comment]
Si me pude entrar en producción
