### ISSUE TITLE
Propuesta de diseño para diferenciar la Infraestructura Estratégica de las propuestas de categorías que haga la gente

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/madison#201]
@diegobeauroyre este es ichu de design, no hay manera de diferenciar qué categorías y bases son parte de la infraestructura estratégica y cuáles son propuestas de la gente

**Comment by rodowi** [comment]
Necesitamos diferenciar los conjuntos propuestos por nosotros de los propuestos por los usuarios

Podemos identificar que posts son del "sponsor" y a esos agregarles el ícono o el diferenciador

**Comment by jipster** [comment]
@diegobeauroyre aquí

**Comment by diegobeauroyre** [comment]
![27cd8864-d873-11e4-8d58-e44ae3d7c7fa](https://cloud.githubusercontent.com/assets/6226604/7035482/ae7c3e3e-dd4e-11e4-8638-5aeeefc7a0ef.jpg)

**Comment by rodowi** [comment]
![screen shot 2015-04-13 at 11 07 38 pm](https://cloud.githubusercontent.com/assets/705860/7130233/f1b7e800-e231-11e4-9bb9-d6a397bd2ef3.png)
