### ISSUE TITLE
Falta feedback al usuario cuando hace una acción

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#203]
P. ej. cuando das like parece que no pasa nada

**Comment by rodowi** [comment]
TODO

- [ ] cuando doy like me deben avisar
- [ ] cuando sugiero un conjunto me deben agradecer

**Comment by diegobeauroyre** [comment]
Feedback de likes/dislike cambia de color. 
Cuando se sugiere un conjunto sale un 

![gob_participa_reddit2-01](https://cloud.githubusercontent.com/assets/6226604/6949690/27d824a4-d873-11e4-9368-80142f484bd2.png)
![gob_participa_reddit2-02](https://cloud.githubusercontent.com/assets/6226604/6949689/27cd8864-d873-11e4-8d58-e44ae3d7c7fa.jpg)

**Comment by diegobeauroyre** [comment]
@jipster
 aquí
