### ISSUE TITLE
Recuperación de password no funciona

### ISSUE THREAD

**Issue by jipster** [mxabierto/madison#205]
Después de tratar de recuperar tu contraseña te manda un link al correo que te manda a un blank page 

![image](https://cloud.githubusercontent.com/assets/5718530/6954506/bca5e44c-d88f-11e4-9ff0-9cdbf0393e03.png)
![image](https://cloud.githubusercontent.com/assets/5718530/6954507/c2158bc6-d88f-11e4-95db-9b155219d4a3.png)

**Comment by rodowi** [comment]
le falta el path /participa/

:angry:

**Comment by rodowi** [comment]
duplicado en #193
