### ISSUE TITLE
Login popup is not displaying error message

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#208]
Not working for comments

![screen shot 2015-04-13 at 6 20 05 pm](https://cloud.githubusercontent.com/assets/705860/7137507/e33170dc-e27f-11e4-87d7-91137a42cfd0.png)

------

Working for annotations

![screen shot 2015-04-13 at 6 20 26 pm](https://cloud.githubusercontent.com/assets/705860/7137516/f2919598-e27f-11e4-8228-3759c274edac.png)

**Comment by codemoe** [comment]
PR has been submitted to Opengov/Madison

https://github.com/opengovfoundation/madison/pull/544

**Comment by rodowi** [comment]
Igual, avanzamos independientemente de Opengov/Madison - allá los PRs se vuelven rancios
