### ISSUE TITLE
Si el tour no se puede traducir - entonces quitarlo

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#41]
![screen shot 2015-01-13 at 11 37 15 pm](https://cloud.githubusercontent.com/assets/705860/5734548/2dd5d9f6-9b7d-11e4-9420-63f8e2369699.png)

**Comment by diegobeauroyre** [comment]
Estoy con la traducción

**Comment by diegobeauroyre** [comment]
Listo #57
