### ISSUE TITLE
Traducir mensajes de signup con redes sociales

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#52]
![screen shot 2015-01-15 at 8 56 11 am](https://cloud.githubusercontent.com/assets/705860/5759770/9244e54e-9c95-11e4-90a9-619ea05c8aa9.png)

**Comment by diegobeauroyre** [comment]
on it

**Comment by diegobeauroyre** [comment]
Listo acá #Traduce mensajes de signup con redes sociales

**Comment by diegobeauroyre** [comment]
Quedó acá: #59

**Comment by rodowi** [comment]
Mira @diegobeauroyre así se ve en producción :dancer: 

![screen shot 2015-01-15 at 1 15 53 pm](https://cloud.githubusercontent.com/assets/705860/5764567/b1044cb8-9cb8-11e4-8f9a-877c0df9fc42.png)
