### ISSUE TITLE
Quitar teléfono en sección de "Configuración de Cuenta"

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/madison#60]
Si te metes a configuración de cuenta, está nombre, cambio de password, URL y teléfono. El teléfono no lo podemos pedir porque no está contemplado en el aviso de privacidad. Lo tendríamos que quitar.

**Comment by diegobeauroyre** [comment]
También quitar URL

**Comment by diegobeauroyre** [comment]
![screen shot 2015-01-15 at 1 00 03 pm](https://cloud.githubusercontent.com/assets/6226604/5764299/7a6a09ce-9cb6-11e4-803a-d57f33d9e0a4.png)

**Comment by rodowi** [comment]
@alejandrardr ya es hacker de github!

fixed by #68

**Comment by alejandrardr** [comment]
Wuuu! \o/
