### ISSUE TITLE
Acciones (iconos) de comentarios no están funcionando

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#61]

**Comment by rodowi** [comment]
En master sí funcionan @cone-7

**Comment by rodowi** [comment]
Esto sólo sucede en un branch. No es issue del proyecto.

**Comment by cone-7** [comment]
Para resolver el issue en el archivo "controller.js", la funcion visibleall del controller "AnnotationController" copiarse sustituirse en el controller "UserPageController", .
