### ISSUE TITLE
Agregar GIF de how-to-annotate en español

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#7]
y que on click haga zoom-out

https://github.com/mxabierto/madison/blob/master/public/img/how-to-annotate.gif

**Comment by diegobeauroyre** [comment]
Gif en español https://drive.google.com/folderview?id=0B6xuFjlJEb0NaFZMdlhkTnNtUTQ&usp=sharing

**Comment by diegobeauroyre** [comment]
logré comprimirlo a 270K quitando keyframes a mano

![](http://rack.0.mshcdn.com/media/ZgkyMDEzLzA4LzA1Lzc4L3RoZWZyZXNocHJpLmJjYjYxLmdpZgpwCXRodW1iCTg1MHg4NTA-CmUJanBn/94861316/e62/the-fresh-prince-of-bel-air.jpg)


![gif_720x480-3](https://cloud.githubusercontent.com/assets/6226604/6066036/789b17e4-ad2f-11e4-9e89-e9d4755ba06f.gif)
