### ISSUE TITLE
Homologar copy con gob.mx

### ISSUE THREAD

**Issue by rodowi** [mxabierto/madison#82]

**Comment by rodowi** [comment]
cc: @diegobeauroyre alguna pista de dónde están estas observaciones?

**Comment by diegobeauroyre** [comment]
Aquí estan los comentarios de gaby: https://docs.google.com/document/d/19iuyGZ2pkSFF-SLqH2tV-iAJ5MA7OLu-THt4Ye7Zkms/edit

**Comment by diegobeauroyre** [comment]
#121
